/**
 * components/chat/suggestions.ts
 * ---------------------------------------------------------------------------
 * Static list of starter prompts shown on the empty New Chat screen. Pure
 * data — extracted from ChatInterface.tsx so the component file no longer
 * carries ~60 lines of copy.
 */
export const ALL_SUGGESTIONS: readonly string[] = [
  'Explain how the agent tool loop works',
  'What can you remember about me?',
  'List all available tools',
  'Help me write a Python script',
  'What MCP servers are connected?',
  'What skills do you have installed?',
  'What is the current date and time in UTC?',
  'Summarise the latest news headlines',
  'Search the web for recent AI research papers',
  "What's the best way to debug a JavaScript async/await issue?",
  'Explain the difference between RAG and fine-tuning',
  'What can you tell me about the Model Context Protocol?',
  'How do I add a new MCP server to this platform?',
  'Help me write a SQL query to find duplicate rows',
  'Explain how streaming works in this chat application',
  'What environment variables are currently set?',
  'Give me a code review checklist for a TypeScript project',
  'Help me plan a software architecture for a SaaS product',
  'Create a new agent that acts as a product manager',
  'Create a new agent that reviews security risks in code',
  'Create a new agent that turns messy notes into action plans',
  'Design a multi-agent workflow for launching a startup website',
  'Ask a researcher agent to compare three database options',
  'Ask a coder agent to prototype a small browser game',
  'Run two sub-agents to solve this issue with different approaches and compare their results',
  'Turn this conversation into durable memory if anything reusable appears',
  'Inspect my agent memory and suggest what should be pruned',
  'Explain what each agent in this workspace is specialized for',
  'Show me the exact system prompt for the current agent',
  'Create an agent that only outputs strict JSON',
  'Create a research-and-extract agent that can use web search before producing JSON',
  'Build a personal chief-of-staff agent with memory and task triage rules',
  'Generate a project folder with an HTML app and open it in preview',
  'Create a one-file interactive dashboard and preview it',
  'Make a sci-fi themed snake game and open the preview panel',
  'Read a file, summarize it, then create follow-up tasks from it',
  'Compare what you can do with built-in tools versus MCP tools',
  'Explain which tools are dangerous and when I should enable them',
  'Use web search to verify a claim, then save the lesson to memory',
  'Research competitors for an idea and output a concise brief',
  'Create a reusable skill for writing better commit messages',
  'Install or configure an MCP server for a new capability',
  'Explain how MCP changes what an agent can do',
  'Use RAG to answer questions from uploaded documents',
  'Tell me what uploaded knowledge sources are available',
  'Build a checklist for safely letting an AI modify files',
  'Read my settings and explain what capabilities are currently enabled',
  'Trace how a user message becomes tool calls and final output',
  'Create a lesson plan for learning agentic AI with this app',
  'Simulate a team of agents solving a product launch problem',
  'Have one agent write a plan and another agent find flaws in it',
  'Generate test cases for an idea before writing code',
  'Find an edge case in my plan that I probably missed',
  'Create a memory policy for what this agent should and should not remember',
  'Generate a concise status report from files in a project folder',
  'Turn a product idea into requirements, tasks, and a first prototype',
  'Create a debugging agent that asks for evidence before proposing fixes',
  'Create a learning coach agent that tracks progress in memory',
  'Make an unexpected creative demo that uses files, preview, and memory',
  'Show me something surprising that an agent with tools can do',
];
